execute pathogen#infect()
syntax on
filetype plugin indent on

" Start plugin manager
call plug#begin('~/.vim/plugged')
Plug 'morhetz/gruvbox'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-sensible'
Plug 'kchmck/vim-coffee-script', { 'for': ['coffee'] }
Plug 'mxw/vim-jsx', { 'for': ['javascript', 'javascript.jsx'] }
Plug 'pangloss/vim-javascript', { 'for': ['javascript', 'javascript.jsx'] }
Plug 'heavenshell/vim-jsdoc', { 'for': ['javascript', 'javascript.jsx'] }
Plug 'wavded/vim-stylus', { 'for': 'stylus' }
Plug 'hynek/vim-python-pep8-indent', { 'for': 'python' }
" Add plugins to &runtimepath
call plug#end()

set background=dark
colorscheme gruvbox
set number

" Source vimrc
nmap <leader>src :so ~/.vim/vimrc<cr>
" Switch windows
nnoremap <Leader>1 <C-w>p
nnoremap <Leader>2 <C-w>w
" set wildignore+=.git,**/libs/**,**/lib/**,**/swagger/**,**/vendor/**,**/jquery/**,**/django_summernote/**,**/assets/**,**/node_modules"

""""""""""""""""""""""""
" * Built in Toggles * "
""""""""""""""""""""""""
" Formatting / Settings
set fileformat=unix     " Make sure the files are always unix
set fileformats=unix    " Make sure the files are always unix
set backspace=2         " make backspace work
set expandtab       	" tabs are spaces (tab button = spaces)
set shiftwidth=4        " number of spaces when shifting block
set softtabstop=4  	    " number of spaces in tab when editing
set tabstop=4 		    " number of visual spaces per TAB

" folding settings
set foldmethod=indent   " fold based on indent
set foldnestmax=10      " deepest fold is 10 levels
set nofoldenable        " dont fold by default
set foldlevel=0         " this is just what i use

" UI configs
set scrolloff=5         " Makes the cursor offset
set colorcolumn=80      " keep within this column
set cursorline          " highlight current line
set lazyredraw          " redraw only when we need to.
set number 		        " show line nums
set showcmd 		    " show last entered command
set showmatch 		    " show matching ()
set wildmenu            " visual autocomplete for command menu


" UI Settings if nvim isn't running
set mouse=a             " Turn on mouse mode
if !has('nvim')
    set ttymouse=xterm2
endif

""""""""""""
" NerdTree " 
""""""""""""
" autocmd vimenter * NERDTree
nmap <leader>nt :NERDTreeToggle<cr>
nmap <leader>st :NERDTreeFind<cr>

"""""""""""
" Control P 
"""""""""""
set runtimepath^=~/.vim/bundle/ctrlp.vim
" Setup some default ignores
let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git' 
" Use the nearest .git directory as the cwd
" This makes a lot of sense if you are working on a project that is in version
" control. It also supports works with .svn, .hg, .bzr.
let g:ctrlp_working_path_mode = 'r'
let g:ctrlp_match_window = 'min:4,max:999'
" Use a leader instead of the actual named binding
nmap <leader>p :CtrlP<cr>
" Easy bindings for its various modes
nmap <leader>pp :CtrlPBuffer<cr>
nmap <leader>bm :CtrlPMixed<cr>
nmap <leader>bs :CtrlPMRU<cr>

"""""""""""
" AIRLINE "
"""""""""""
" This allows buffers to be hidden if you've modified a buffer.
" This is almost a must if you wish to use buffers in this way.
set hidden
" Enable the list of buffers
let g:airline#extensions#tabline#enabled = 1
" Show just the filename
let g:airline#extensions#tabline#fnamemod = ':t'
" To open a new empty buffer
" This replaces :tabnew which I used to bind to this mapping
nmap <leader>T :enew<cr>
" Move to the next buffer
nmap <Tab> :bnext<CR>
nmap <S-Tab> :bprevious<CR>
" nmap <leader>l :bnext<CR>
" nmap <leader>] :bnext<CR>
" " Move to the previous buffer
" nmap <leader>h :bprevious<CR>
" nmap <leader>[ :bprevious<CR>
" Close the current buffer and move to the previous one
" This replicates the idea of closing a tab
nmap <leader>bq :bp <BAR> bd #<CR>
" Show all open buffers and their status
nmap <leader>bl :ls<CR>


"""""""""""""
" SYNTACTIC "
"""""""""""
" set statusline+=%#warningmsg#
" set statusline+=%{SyntasticStatuslineFlag()}
" set statusline+=%*
" " let g:syntastic_always_populate_loc_list = 1
" " let g:syntastic_auto_loc_list = 1
" let g:syntastic_check_on_open = 1
" let g:syntastic_check_on_wq = 0
" let g:syntastic_python_checkers = ['flake8', 'pyflakes', 'pylint', 'python']
" let g:syntastic_javascript_checkers = ['eslint']

